require 'test/unit/testsuite'

require 'tc_profile'
require 'tc_albumsv9'
require 'tc_mediaItemsv9'
require 'tc_notificationsv9'
require 'tc_statusMoodv9'
require 'tc_peoplev9'
require 'tc_groupsv9'
require 'tc_appdatav9'
require 'tc_activitiesv9'
require 'tc_mediaItemCommentsv9'